CREATE TABLE IF NOT EXISTS categories(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(60) NOT NULL,
	description VARCHAR(120) DEFAULT NULL,
	slug VARCHAR(60) NOT NULL,
	created_at DATETIME NOT NULL,
	deleted_at DATETIME DEFAULT NULL,
	UNIQUE KEY(slug)
);